SonarCloud Fail first try

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -57,4 +57,9 @@ jobs:
           dotnet tool install -g dotnet-sonarscanner
           dotnet-sonarscanner begin /k:"FilipiBraga_SumUpArrayElements" /o:"filipibc" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
           dotnet build --configuration Release
-          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"        
+          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+      - name: Check for errors
+        if: error()
+        run: |
+          echo "SonarCloud analysis failed."
+          exit 1
